### ISSUE TITLE
I didn't get anything from tutorial

### ISSUE THREAD

**Issue by safran1** [6ag/jiansan-laravel#2]
Hi,
I read the tutorial a 100 times but I didn't understand anything... Can you help me?

**Comment by safran1** [comment]
My host is openshift..
By redhat

**Comment by 6ag** [comment]
Hi, You can refer to https://laravel.com/docs/5.2/installation.

**Comment by 6ag** [comment]
Deployment laravel operating environment on a server, you need to install the composer.

**Comment by safran1** [comment]
Is there a free host for laravel or something?
I was using openshift but I created 3 gears and I must pay to add another gear...
Or I must delete ios gear which I can't right now....

**Comment by safran1** [comment]
Or at least a cheap one

**Comment by safran1** [comment]
I found laravel 5.2 catriadge for openshift
But is php 5.4 and mysql 5.5 ok?

**Comment by 6ag** [comment]
It requires more than php5.6.

**Comment by safran1** [comment]
Now,
I have php >5.6
MySql > 5.7
Nginx > 1.8
And I copied the represitory to my host,,,
(git push)
But it does not read anything
404 Not Found

nginx/1.11.1

**Comment by 6ag** [comment]
nginx needs to point to the root directory of public projects laravel.

for example:   

``` shell
server {
listen 80;
server_name jiansan.6ag.cn;
access_log off;
index index.html index.htm index.php;
root /data/wwwroot/jiansan.6ag.cn/jiansan-laravel/public;
```

**Comment by safran1** [comment]
server {
    listen  127.5.253.129:8080;
    root    /var/lib/openshift/57aae05c89f5cf06770000b6/app-root/runtime/repo/public;

```
location / {
    index  index.html index.htm index.php;
}
```

}

Hi,
These information are in nginx_http.conf
It is pointed to root directory of public
and I tried adding to index   index.php
But it is still forbidden

**Comment by safran1** [comment]
Well,
It reads index.html 
but not index.php

**Comment by safran1** [comment]
Nevermind
I solved it
But index.php
has problems
