### ISSUE TITLE
Can't upload photo

### ISSUE THREAD

**Issue by safran1** [6ag/jiansan-laravel#5]
I can't upload photo.
Always returning unknown error

And laravel.log is returning that

[2016-09-09 16:23:39] local.ERROR: ReflectionException: Class App\Http\Controllers\Admin\WallPaperController does not exist in /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Route.php:280
Stack trace:
#0 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Route.php(280): ReflectionMethod->__construct('App\Http\Contro...', 'upload')
#1 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(857): Illuminate\Routing\Route->signatureParameters('Illuminate\Data...')
#2 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(842): Illuminate\Routing\Router->substituteImplicitBindings(Object(Illuminate\Routing\Route))
#3 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(825): Illuminate\Routing\Router->substituteBindings(Object(Illuminate\Routing\Route))
#4 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(691): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#5 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#6 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(246): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#8 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#10 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#13 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /var/lib/openshift/secret/app-root/runtime/repo/vendor/dingo/api/src/Http/Middleware/Request.php(108): Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: Dingo\Api\Http\Middleware\Request->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(136): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#18 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#20 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /var/lib/openshift/secret/app-root/runtime/repo/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#23 /var/lib/openshift/secret/app-root/runtime/repo/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#24 {main}

**Comment by 6ag** [comment]
Picture upload process I use `intervention-image` , link is https://github.com/Intervention/image.

**Comment by safran1** [comment]
Can you give me an example of where and how did you use it?

**Comment by 6ag** [comment]
You need to make sure that it meets the following requirements:

extension:
Fileinfo Extension
GD Library (>=2.0)
Imagick PHP extension (>=6.5.7)

public/uploads 777

However, if you can not use, you can try
![image](https://cloud.githubusercontent.com/assets/9330618/18383204/009455d2-76b7-11e6-9938-af02ac59b6e4.png)

**Comment by safran1** [comment]
In wallpapercontroller.php ???
