### ISSUE TITLE
请教一下controller里的注释是如何生成的？

### ISSUE THREAD

**Issue by klgd** [6ag/jiansan-laravel#6]
是用什么工具生成的还是手动编写的？

**Comment by 6ag** [comment]
手动编写的

**Comment by klgd** [comment]
@6ag 那好麻烦啊 尤其是 json格式数据，这很不好排版啊

**Comment by 6ag** [comment]
我也是这样觉得的，但是没办法的。这个注释格式是按照第三方文档扩展包来写的，只能手动。因为参数 返回字段 返回json等等数据是只有编写的人才知道的。
